[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 99
target-version = ['py37']
skip-string-normalization = true

[tool.coverage.run]
branch = true
source = ["pgtrigger"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "raise AssertionError",
    "raise NotImplementedError",
    "pass",
    "pytest.mark.slow"
]
show_missing = true
fail_under = 100

[tool.poetry]
name = "django-pgtrigger"
packages = [
  { include = "pgtrigger" }
]
version = "2.4.0"
description = "Postgres trigger support integrated with Django models."
authors = ["Wes Kendall"]
classifiers = [
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3 :: Only",
  "Framework :: Django",
]
license = "BSD-3-Clause"
readme = "README.rst"
homepage = "https://github.com/Opus10/django-pgtrigger"
repository = "https://github.com/Opus10/django-pgtrigger"
documentation = "https://django-pgtrigger.readthedocs.io"

[tool.poetry.dependencies]
python = ">=3.7.0,<4"
django = ">=2"
django-pgconnection = ">=1.0.1"

[tool.poetry.dev-dependencies]
black = "22.1.0"
dj-database-url = "0.5.0"
django-dynamic-fixture = "3.1.2"
flake8 = "3.9.2"
flake8-bugbear = "22.1.11"
flake8-comprehensions = "3.8.0"
flake8-import-order = "0.18.1"
flake8-logging-format = "0.6.0"
flake8-mutable = "1.2.0"
git-tidy = "1.1.2"
packaging = ">=19.2"
psycopg2-binary = "2.9.3"
pytest = "7.0.0"
pytest-cov = "3.0.0"
pytest-django = "4.5.2"
pytest-mock = "3.7.0"
Sphinx = "4.4.0"
sphinx-rtd-theme = "1.0.0"
temple = "*"
tox = "3.24.5"

[tool.pytest.ini_options]
xfail_strict = true
addopts = "--reuse-db"
testpaths = "pgtrigger/tests"
norecursedirs = ".venv"
DJANGO_SETTINGS_MODULE = "settings"
